services:
  orbitweb:
    image: "gurudohimalaia/orbitweb:latest"
    container_name: "OrbitWeb"

    restart: always

    ports:
      - "9031:8080"

    environment:
      ORBIT_API_URL: ${ORBIT_API_URL}
